version: "3.11"

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./project:/project
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"