version: "3.11"

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./project:/project
    command: >
      sh -c "python manage.py wait_for_db && 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=recipeproject
      - DB_USER=george
      - DB_PASSWORD=password
    depends_on:
      - database
    restart: unless-stopped
  
  database:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/data/postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=recipeproject
      - POSTGRES_USER=george
      - POSTGRES_PASSWORD=password
      - PGDATA= /data/postgres

volumes:
  dev-db-data: